### ISSUE TITLE
hydros build image gives error https scheme is not supported

### ISSUE THREAD

**Issue by jlewi** [jlewi/hydros#81]
Here's the yaml

```
kind: Image
apiVersion: hydros.dev/v1alpha1
metadata:
  name: frontend
  namespace: foyle
  labels:
    env: dev
spec:
  image: us-west1-docker.pkg.dev/foyle-public/images/frontend
  source:
    - uri: https://github.com/jlewi/foyle.git
      mappings:
        - src: "/frontend/**/*"
  builder:
    gcb:
      project: foyle-public
      bucket : builds-foyle-public
      machineType: 'E2_HIGHCPU_8'
      dockerfile: /frontend/Dockerfile
```

Here's the stacktrace

```
Scheme https is not supported
github.com/jlewi/hydros/pkg/tarutil.copyLocalPath
	/Users/jlewi/git_hydros/pkg/tarutil/builder.go:96
github.com/jlewi/hydros/pkg/tarutil.Build
	/Users/jlewi/git_hydros/pkg/tarutil/builder.go:77
github.com/jlewi/hydros/pkg/images.(*Controller).Reconcile
	/Users/jlewi/git_hydros/pkg/images/controller.go:170
github.com/jlewi/hydros/pkg/images.ReconcileFile
	/Users/jlewi/git_hydros/pkg/images/controller.go:485
github.com/jlewi/hydros/cmd/commands.NewBuildCmd.func1
	/Users/jlewi/git_hydros/cmd/commands/build.go:20
github.com/spf13/cobra.(*Command).execute
	/Users/jlewi/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944
github.com/spf13/cobra.(*Command).ExecuteC
	/Users/jlewi/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068
github.com/spf13/cobra.(*Command).Execute
	/Users/jlewi/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main
	/Users/jlewi/git_hydros/cmd/main.go:151
runtime.main
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/proc.go:267
runtime.goexit
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/asm_arm64.s:1197
Failed to create tarball gs://builds-foyle-public/foyle-public/images/frontend.462efa18251584f9404a960132d62aa76ba1056a.tgz
github.com/jlewi/hydros/pkg/images.(*Controller).Reconcile
	/Users/jlewi/git_hydros/pkg/images/controller.go:171
github.com/jlewi/hydros/pkg/images.ReconcileFile
	/Users/jlewi/git_hydros/pkg/images/controller.go:485
github.com/jlewi/hydros/cmd/commands.NewBuildCmd.func1
	/Users/jlewi/git_hydros/cmd/commands/build.go:20
github.com/spf13/cobra.(*Command).execute
	/Users/jlewi/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944
github.com/spf13/cobra.(*Command).ExecuteC
	/Users/jlewi/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068
github.com/spf13/cobra.(*Command).Execute
	/Users/jlewi/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main
	/Users/jlewi/git_hydros/cmd/main.go:151
runtime.main
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/proc.go:267
runtime.goexit
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/asm_arm64.s:1197
```
